// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBKDnRgsajjAOiR3nB-dOcnUfrKKrYKHQ',
    appId: '1:878878860837:web:69d314c789928bbde681cc',
    messagingSenderId: '878878860837',
    projectId: 'find-room-5c1df',
    authDomain: 'find-room-5c1df.firebaseapp.com',
    storageBucket: 'find-room-5c1df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChRswI_V6wnCl-JIAX96IzMiB60AZYDNk',
    appId: '1:878878860837:android:d58a410d306c2228e681cc',
    messagingSenderId: '878878860837',
    projectId: 'find-room-5c1df',
    storageBucket: 'find-room-5c1df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3TlWEa6to2bDoqUf7UDKYzO_thRfjukQ',
    appId: '1:878878860837:ios:e0eb54e5fd67886de681cc',
    messagingSenderId: '878878860837',
    projectId: 'find-room-5c1df',
    storageBucket: 'find-room-5c1df.appspot.com',
    iosClientId: '878878860837-dllkau0enlloh3m14jvpov8s92er1f49.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRoomGuide',
  );
}
